---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:

  use-pinned-version:
    desc: Use the pinned version of Open Tofu.
    vars:
      TOFU_PIN_FILE: '{{.ROOT_DIR}}/.opentofu-version'
      TOFU_VERSION:
        sh: cat {{.TOFU_PIN_FILE}}
    cmds:
      - tofuenv install {{.TOFU_VERSION}}
      - tofuenv use {{.TOFU_VERSION}}
    preconditions:
      - which tofuenv
      - test -f {{.TOFU_PIN_FILE}}
    sources:
      - '{{.TOFU_PIN_FILE}}'

  fix:
    desc: Runs formatting, linting, and doc generation on all tofu modules.
    vars:
      MODULES:
        sh: 'ls {{.MODULES_DIR}}'
    cmds:
      - task: use-pinned-version
      - for: { var: MODULES }
        task: lint-{{.ITEM}}
      - for: { var: MODULES }
        task: format-{{.ITEM}}
      - for: { var: MODULES }
        task: docs-{{.ITEM}}

  check:
    desc: Runs all the checks for all modules.
    vars:
      MODULES:
        sh: 'ls {{.MODULES_DIR}}'
    cmds:
      - task: use-pinned-version
      - for: { var: MODULES }
        task: lint-{{.ITEM}}
        vars:
          FIX: "false"
      - for: { var: MODULES }
        task: format-{{.ITEM}}
        vars:
          FIX: "false"
      - for: { var: MODULES }
        task: docs-{{.ITEM}}
        vars:
          FIX: "false"

  lint-*:
    label: lint-{{.MODULE}}
    desc: Lints the tofu configuration files.
    vars:
      MODULE: "{{index .MATCH 0}}"
      MODULE_PATH: "{{.MODULES_DIR}}/{{.MODULE}}"
      FIX: '{{.FIX | default "true"}}'
    cmds:
      - tflint --version
      - tflint --chdir={{.MODULE_PATH}} --recursive {{if eq .FIX "true"}}--fix{{end}}
    preconditions:
      - which tflint
    sources:
      - '{{.MODULE_PATH}}/**/*.tf'
  
  format-*:
    desc: Formats the tofu configuration files.
    label: format-{{.MODULE}}
    vars:
      MODULE: "{{index .MATCH 0}}"
      MODULE_PATH: "{{.MODULES_DIR}}/{{.MODULE}}"
      FIX: '{{.FIX | default "true"}}'
    cmds:
      - task: use-pinned-version
      - tofu fmt {{if eq .FIX "false"}}-check{{end}} -recursive {{.MODULE_PATH}}   
    preconditions:
      - which tofu
    sources:
      - '{{.MODULE_PATH}}/**/*.tf'
    
  docs-*:
    desc: Generates docs for tofu modules.
    label: docs-{{.MODULE}}
    vars:
      MODULE: "{{index .MATCH 0}}"
      MODULE_PATH: "{{.MODULES_DIR}}/{{.MODULE}}"
    cmds: 
      - terraform-docs --version
      - terraform-docs markdown --output-file {{.MODULE_PATH}}/README.md {{if eq .FIX "false"}} --output-check {{end}} {{.MODULE_PATH}} 
    preconditions:
      - which terraform-docs
    sources:
      - '{{.MODULE_PATH}}/**/*.tf'
    generates:
      - '{{.MODULE_PATH}}/README.md'

  validate-*:
    desc: Validates the tofu configuration files for a specific module.
    label: validate-{{.MODULE}}
    vars:
      MODULE: "{{index .MATCH 0}}"
    cmds:
      - task: use-pinned-version
      - tofu -chdir={{.MODULES_DIR}}/{{.MODULE}} init -upgrade
      - tofu -chdir={{.MODULES_DIR}}/{{.MODULE}} validate
    preconditions:
      - which tofu
    sources:
      - '{{.MODULES_DIR}}/{{.MODULE}}/**/*.tf'
