---
schemaVersion: "2.0.0"
fileExistenceTests:
  - name: "Check flock binary exists"
    path: "/usr/bin/flock"
    shouldExist: true
    
  - name: "Check tofu binary exists"
    path: "/usr/local/bin/tofu"
    shouldExist: true
    permissions: "-rwxr-xr-x"

commandTests:
  - name: "Check flock is executable and shows help"
    command: "flock"
    args: ["--version"]
    expectedOutput:
      - "flock"  
    exitCode: 0

  - name: "Check tofu version"
    command: "tofu"
    args: ["--version"]
    expectedOutput:
      - "OpenTofu"
    exitCode: 0

  - name: "Check yq version"
    command: "yq"
    args: ["--version"]
    expectedOutput:
      - "yq"
    exitCode: 0