# OpenTofu
tap 'tofuutils/tap'
brew 'tgenv'
brew 'tofuenv'
brew "tflint" # Does not officially support OpenTofu https://github.com/terraform-linters/tflint/issues/2194#issuecomment-2558127231
brew "terraform-docs"

# Flock, required for modules/talos-cluster/resources/scripts/upgrade-node.sh
brew "flock"