---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  brew:
    desc: Set up Homebrew tools
    vars:
      BREWFILE: '{{.ROOT_DIR}}/Brewfile'
    cmds:
      - brew bundle --file {{.BREWFILE}}
    sources:
      - '{{.BREWFILE}}'
    generates:
      - '{{.BREWFILE}}.lock.json'
    preconditions:
      - which brew
      - test -f {{.BREWFILE}}
