version: "3"

tasks:
  pull-request:
    desc: Runs the github pull request workflow locally.
    cmds:
      - act pull_request
  build-container:
    desc: Builds the build container.
    vars:
      IMAGE: homelab-modules-runner
      PATH: '{{.ROOT_DIR}}'
      VERSION: '2.324.0'
      PLATFORM: linux/amd64
    cmds:
      - docker build {{.PATH}} --build-arg VERSION={{.VERSION}} --platform={{.PLATFORM}} -t {{.IMAGE}}
      - container-structure-test test --image {{.IMAGE}} --platform={{.PLATFORM}} --config {{.PATH}}/tests.yaml