version: "3"

vars:
  IMAGE: homelab-modules-runner:local
  PLATFORM: linux/amd64


tasks:
  pull-request:
    desc: Runs the github pull request workflow locally.
    cmds:
      - act pull_request
  build-container:
    desc: Builds the build container.
    vars:
      PATH: '{{.ROOT_DIR}}'
    cmds:
      - docker buildx bake image-local --set image.tags={{.IMAGE}}
      - container-structure-test test --image {{.IMAGE}} --platform={{.PLATFORM}} --config {{.PATH}}/tests.yaml
  run-container:
    desc: Runs the docker container.
    cmds:
      - docker run --platform {{.PLATFORM}} -it --rm {{.IMAGE}} /bin/bash