version: "3"

vars:
  IMAGE: homelab-modules-runner:local
  PLATFORM: linux/amd64


tasks:
  pull-request:
    desc: Runs the github pull request workflow locally.
    cmds:
      - act pull_request
  build-container:
    desc: Builds the build container.
    vars:
      PATH: '{{.ROOT_DIR}}'
    cmds:
      - docker buildx bake image-local --set image.tags={{.IMAGE}}
      - container-structure-test test --image {{.IMAGE}} --platform={{.PLATFORM}} --config {{.PATH}}/tests.yaml
  run-container:
    desc: Runs the docker container.
    cmds:
      - docker run --platform {{.PLATFORM}} -it --rm {{.IMAGE}} /bin/bash
  get-remote-kubeconfig:
    desc: gets the remote kubeconfig
    vars:
      CLUSTER: intent-cub
    cmd: |
      aws ssm get-parameter \
        --name /homelab/infrastructure/clusters/integration/{{.CLUSTER}}/kubeconfig \
        --with-decryption \
        --query 'Parameter.Value' \
        --output text \
        --profile terragrunt \
        --region us-east-2 \
      > ~/.kube/testing/{{.CLUSTER}}.yaml 
  get-remote-talosconfig:
    desc: gets the remote talosconfig
    vars:
      CLUSTER: intent-cub
    cmd: |
      aws ssm get-parameter \
        --name /homelab/infrastructure/clusters/integration/{{.CLUSTER}}/talosconfig \
        --with-decryption \
        --query 'Parameter.Value' \
        --output text \
        --profile terragrunt \
        --region us-east-2 \
      > ~/.talos/testing/{{.CLUSTER}}.yaml 