---
name: Run Tofu Test
description: Run tests associated with modules.
inputs:
  tofu_version:
    description: 'The version of Tofu to use'
    required: true
    default: '1.8.8'
runs:
  using: composite
  steps:
    - name: Setup Taskfile
      uses: Illbjorn/setup-task@0.1.0
    - name: Setup Tofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: ${{ inputs.tofu_version}}
