# Required for modules/talos-cluster/resources/scripts/upgrade-node.sh
tap "siderolabs/tap"
brew "talosctl"
brew "flock"
brew "jq"
brew "yq"

# OpenTofu
brew "opentofu"
brew "tflint"
brew "terraform-docs"
