---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Bump Tagged Version
on:
  push:
    paths:
      - 'modules/**/*.tf'
    branches:
      - main
jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
