---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Container Release

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'Dockerfile'
      - 'docker-bake.hcl'

jobs:
  container-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Bake & push multi-arch image
        uses: docker/bake-action@v6
        with:
          push: true
          set: |
            *.output=type=registry
            *.tags=ghcr.io/${{ github.repository_owner }}/homelab-modules-runner:latest