---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    uses: ./.github/workflows/container-validate.yml