---
name: Pull Request CI Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/**'

env:
  tofu_version: '1.8.8'
  terraform_docs_version: 'v0.18.0'
  tflint_version: 'v0.47.0'

jobs:
  tofu-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tofu CI
        uses: ./.github/actions/tofu-ci
        with:
          tofu_version: ${{ env.tofu_version }}
          terraform_docs_version: ${{ env.terraform_docs_version }}
          tflint_version: ${{ env.tflint_version }}