---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  container-validate:
    uses: ./.github/workflows/container-validate.yaml

  tofu-validate:
    uses: ./.github/workflows/tofu-validate.yaml