---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Allow create workflow dispatch events
      pull-requests: write  # For doing the emoji reaction on a PR comment
      issues: write  # For doing the emoji reaction on an issue comment
      contents: write  # For executing the repository_dispatch event
    steps:
      - uses: xt0rted/pull-request-comment-branch@v3
        id: comment-branch

      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # https://github.com/peter-evans/slash-command-dispatch/issues/147
          permission: admin
          commands: |
            test
          dispatch-type: workflow
          static-args: |
            ref=${{ steps.comment-branch.outputs.head_ref }}
            base=${{ steps.comment-branch.outputs.base_ref }}

      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}