name: Talos Maintenance Mode Test

on:
  workflow_dispatch:

jobs:
  talosctl-maintenance:
    runs-on: homelab-modules-runner-app
    steps:
      - name: Debug tofu binary1
        run: |
          echo "Tofu path: $(which tofu)"
          head -n 1 $(which tofu)
          file $(which tofu)
      - name: Checkout current branch
        uses: actions/checkout@v4
      - name: Setup Taskfile
        uses: Illbjorn/setup-task@0.1.0
        
      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: '1.8.8'
      - name: Debug tofu binary2
        run: |
          echo "Tofu path: $(which tofu)"
          head -n 1 $(which tofu)
          file $(which tofu)

      - name: Tofu Test
        run: |
          tofu --version
          tofu -chdir=modules/kubevirt-talos-hosts init -upgrade
          tofu -chdir=modules/kubevirt-talos-hosts test -filter=tests/main.tftest.hcl

      - name: Install talosctl
        run: |
          mkdir -p /home/runner/_work/tools
          curl -sL https://github.com/siderolabs/talos/releases/latest/download/talosctl-linux-amd64 \
            -o /home/runner/_work/tools/talosctl
          chmod +x /home/runner/_work/tools/talosctl

      - name: Test Talos node in maintenance mode (insecure)
        run: |
          /home/runner/_work/tools/talosctl \
            -n talos-cp01-service.default.svc.cluster.local \
            get disks --insecure
