name: Talos Maintenance Mode Test

on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      test_matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate Test Matrix
        id: set-matrix
        run: |
          files=$(find modules -type f -path "*/tests/*.tftest.hcl" | jq -R . | jq -s .)
          echo "matrix={\"testfile\":$files}" >> "$GITHUB_OUTPUT"

  tofu-test:
    needs: generate-matrix
    runs-on: homelab-modules-runner-app
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.test_matrix) }}
    name: Tofu Test ${{ matrix.testfile }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Test
        run: |
          testfile="${{ matrix.testfile }}"
          module_dir=$(dirname "$(dirname "$testfile")")
          echo "Testing $testfile in $module_dir with filter $(basename "$testfile")"

  talosctl-maintenance:
    runs-on: homelab-modules-runner-app
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        
      - name: Tofu Check
        shell: sh
        run: |
          tofu --version

      - name: Tofu Test
        shell: sh
        run: |
          tofu --version
          tofu -chdir=modules/kubevirt-talos-hosts init -upgrade
          tofu -chdir=modules/kubevirt-talos-hosts test -filter=tests/main.tftest.hcl